// Redux actions
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'FETCH_ALL_POSTS_FAILURE';
export const FETCH_FAVORITE_POSTS = 'FETCH_FAVORITE_POSTS';
export const FETCH_FAVORITE_POSTS_SUCCESS = 'FETCH_FAVORITE_POSTS_SUCCESS';
export const FETCH_FAVORITE_POSTS_FAILURE = 'FETCH_FAVORITE_POSTS_FAILURE';
export const FLUSH_FAVORITE_POSTS = 'FLUSH_FAVORITE_POSTS';
export const FLUSH_ALL_POSTS = 'FLUSH_ALL_POSTS';